org.gradle.jvmargs=-Xmx2G
org.gradle.java.installations.paths=/home/icho/.local/share/jdks/zulu25.36.205-ca-jdk25.0.4.1-linux_x64

# Fabric Properties
minecraft_version=1.21.11
loader_version=0.19.5
loom_version=1.16.2

# Mod Properties
mod_version=1.0.0
maven_group=us.movy
archives_base_name=moondlc

# Dependencies
fabric_api_version=0.141.6+1.21.11
